require('!!file-loader?name=index.html!../../index.html');
module.exports = {
  js: {
    html5shiv: require('!!file-loader?name=static/js/[name].[ext]!../../../vendor/ie-fix/html5shiv.min.js'),
    respond: require('!!file-loader?name=static/js/[name].[ext]!../../../vendor/ie-fix/respond.min.js'),
    jquery: require('!!file-loader?name=static/js/[name].[ext]!jquery/dist/jquery.min.js'),
  },
  images: {
    // 'login-bg': require('!!file-loader?name=static/images/[name].[ext]!../imgs/login-bg.jpg'),
    'slogan': require('!!file-loader?name=static/images/[name].[ext]!../imgs/header/slogan.png'),
    'enSlogan': require('!!file-loader?name=static/images/[name].[ext]!../imgs/footer/en-slogan.png'),
    'contactLogo': require('!!file-loader?name=static/images/[name].[ext]!../imgs/footer/contact-logo.png'),
    'contactCode': require('!!file-loader?name=static/images/[name].[ext]!../imgs/footer/contact-code.jpg'),
    'index-bg': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/banner.jpg'),
    'air-test': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/airTest.png'),
    'formaldehyde': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/Formaldehyde.png'),
    'newsystem': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/newSystem.png'),
    'product1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product1.png'),
    'product2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product2.png'),
    'product3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product3.png'),
    'product4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product4.png'),
    'smbanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/smbanner.png'),
    'case1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case1.jpg'),
    'case2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case2.jpg'),
    'case3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case3.jpg'),
    'case4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case4.jpg'),
    'case5': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case5.jpg'),
    'honor1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor1.jpg'),
    'honor2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor2.jpg'),
    'honor3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor3.jpg'),
    'honor4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor4.jpg'),
    'honor5': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor5.jpg'),
    'advantage1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage1.png'),
    'advantage2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage2.png'),
    'advantage3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage3.png'),
    'advantage4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage4.png'),
    'news-carousel1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/newsCarousel1.jpg'),
    'carInner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/treatment/carInner.png'),
    'roomInner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/treatment/roomInner.png'),
    'danger': require('!!file-loader?name=static/images/[name].[ext]!../imgs/treatment/danger.png'),
    'process': require('!!file-loader?name=static/images/[name].[ext]!../imgs/treatment/process.png'),
    'trBanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/treatment/banner.jpg'),
    'sysBanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/banner.jpg'),
    'sysBrand': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/brand.png'),
    'sysFocus': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/focus.png'),
    'sysAdvanced': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/advanced.png'),
    'sysAfterService': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/afterService.png'),
    'sysProduct1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/product1.jpg'),
    'sysFog': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/fog.jpg'),
    'sysLoveStudent': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/loveStudent.jpg'),
    'sysLoveStuff': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/loveStuff.jpg'),
    'sysLoveOlder': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/loveOlder.jpg'),
    'sysLovePregnant': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/lovePregnant.jpg'),
    'sysLoveBaby': require('!!file-loader?name=static/images/[name].[ext]!../imgs/newSystem/loveBaby.jpg'),
    'testBanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/testBanner.jpg'),
    'testDesc': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/desc.png'),
    'testStandard1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/standard1.jpg'),
    'testStandard2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/standard2.jpg'),
    'testStandard3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/standard3.jpg'),
    'testStandard4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/airTest/standard4.jpg'),
    'proBanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenterDetail/proBanner.jpg'),
    'proDetailDesc': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenterDetail/proDesc.jpg'),
    'proDetailShow': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenterDetail/proShow.png'),
    'proDetailSubmit': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenterDetail/proSubmit.png'),
    'proProduct1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenter/product1.jpg'),
    'proProduct2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenter/product2.jpg'),
    'proProduct3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/productCenter/product3.jpg'),
  },
  // dll: {
  //   js: require('!!file-loader?name=dll/dll.js!../../dll/dll.js'),
  //   css: require('!file-loader?name=dll/dll.css!../../dll/dll.css'),
  // },
};
