require('!!file-loader?name=index.html!../../index.html');
module.exports = {
  js: {
    html5shiv: require('!!file-loader?name=static/js/[name].[ext]!../../../vendor/ie-fix/html5shiv.min.js'),
    respond: require('!!file-loader?name=static/js/[name].[ext]!../../../vendor/ie-fix/respond.min.js'),
    jquery: require('!!file-loader?name=static/js/[name].[ext]!jquery/dist/jquery.min.js'),
  },
  images: {
    // 'login-bg': require('!!file-loader?name=static/images/[name].[ext]!../imgs/login-bg.jpg'),
    'index-bg': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/banner.jpg'),
    'air-test': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/airTest.png'),
    'formaldehyde': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/Formaldehyde.png'),
    'newsystem': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/newSystem.png'),
    'product1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product1.png'),
    'product2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product2.png'),
    'product3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product3.png'),
    'product4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/product4.png'),
    'smbanner': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/smbanner.png'),
    'case1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case1.jpg'),
    'case2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case2.jpg'),
    'case3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case3.jpg'),
    'case4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case4.jpg'),
    'case5': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/case5.jpg'),
    'honor1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor1.jpg'),
    'honor2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor2.jpg'),
    'honor3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor3.jpg'),
    'honor4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor4.jpg'),
    'honor5': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/honor5.jpg'),
    'advantage1': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage1.png'),
    'advantage2': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage2.png'),
    'advantage3': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage3.png'),
    'advantage4': require('!!file-loader?name=static/images/[name].[ext]!../imgs/index/advantage4.png'),
  },
  // dll: {
  //   js: require('!!file-loader?name=dll/dll.js!../../dll/dll.js'),
  //   css: require('!file-loader?name=dll/dll.css!../../dll/dll.css'),
  // },
};
